--FIRST BUSINESS REPORT
SELECT VINNUMBER,MAKE,MODEL,COLOR,PLATENUMBER,MILEAGE,TRANSMISSIONTYPE,VEHICLESTATUS
FROM VEHICLES_IN_MAINTENANCE
WHERE VEHICLESTATUSID = 'M1';

--SECOND BUSINESS REPORT
SELECT VINNUMBER,MAKE,MODEL,COLOR,PLATENUMBER,TRANSMISSIONTYPE,ASSIGNEDAGENCYID,VEHICLESTATUS
FROM VEHICLES_TO_MAINTAIN
WHERE NOT VEHICLESTATUSID = 'M1' AND MILEAGE > 100000;

--THIRD BUSINESS REPORT
SELECT VINNUMBER,MAKE,MODEL,COLOR,PLATENUMBER,DAILYRENTALCOST,ASSIGNEDAGENCYID,CURRENTAGENCYID,VEHICLETYPE,VEHICLESTATUS
FROM VEHICLE_STATUS_VIEW
WHERE VEHICLESTATUSID = 'R1';

--FOURTH BUSINESS REPORT
SELECT VINNUMBER,MAKE,MODEL,COLOR,PLATENUMBER,DAILYRENTALCOST,ASSIGNEDAGENCYID,CURRENTAGENCYID,VEHICLETYPE,VEHICLESTATUS
FROM VEHICLE_STATUS_VIEW
WHERE VEHICLESTATUSID = 'R2';

--FIFTH BUSINESS REPORT
SELECT VINNUMBER,MAKE,MODEL,COLOR,PLATENUMBER,DAILYRENTALCOST,ASSIGNEDAGENCYID,CURRENTAGENCYID,VEHICLETYPE,VEHICLESTATUS
FROM VEHICLE_STATUS_VIEW
WHERE VEHICLESTATUSID = 'A1';

--SIXTH BUSINESS REPORT
SELECT CONFIRMATIONID,DRIVERLICENSENUM,FIRSTNAME,LASTNAME,EMAIL,RESERVATIONSTATUS
FROM RESERVATION_STATUS_VIEW
WHERE RESERVATIONSTATUSID = 'B3';

--SEVENTH BUSINESS REPORT
SELECT CONFIRMATIONID,DRIVERLICENSENUM,FIRSTNAME,LASTNAME,EMAIL,RESERVATIONSTATUS
FROM RESERVATION_STATUS_VIEW
WHERE RESERVATIONSTATUSID = 'A4';

--EIGTH BUSINESS REPORT
SELECT CONFIRMATIONID,DRIVERLICENSENUM,FIRSTNAME,LASTNAME,EMAIL,RESERVATIONSTATUS
FROM RESERVATION_STATUS_VIEW
WHERE RESERVATIONSTATUSID = 'A5';

--NINTH BUSINESS REPORT
SELECT DRIVERLICENSENUM,FIRSTNAME,LASTNAME,EMAIL,EZPLUSNUMBER,EZPLUSEARNEDPOINTS
FROM EARNED_DISCOUNTS
WHERE EZPLUSEARNEDPOINTS > 150;

--TENTH BUSINESS REPORT
SELECT DRIVERLICENSENUM,FIRSTNAME,LASTNAME,EMAIL,EZPLUSNUMBER,EZPLUSEARNEDPOINTS
FROM EARNED_DISCOUNTS
WHERE EZPLUSEARNEDPOINTS < 150 AND EZPLUSEARNEDPOINTS > 100;
