--FIRST VIEW
CREATE VIEW Vehicles_In_Maintenance AS 
 SELECT VEHICLE.VINNUMBER,VEHICLE.MAKE,VEHICLE.MODEL,VEHICLE.COLOR,VEHICLE.PLATENUMBER,VEHICLE.MILEAGE,VEHICLE.TRANSMISSIONTYPE,VEHICLE_STATUS.VEHICLESTATUS,
 VEHICLE_STATUS.VEHICLESTATUSID
 FROM VEHICLE, VEHICLE_STATUS
 WHERE VEHICLE.VEHICLESTATUSID = VEHICLE_STATUS.VEHICLESTATUSID;
 
--SECOND VIEW
CREATE VIEW Vehicles_To_Maintain AS
 SELECT VEHICLE.VINNUMBER,VEHICLE.MAKE,VEHICLE.MODEL,VEHICLE.COLOR,VEHICLE.PLATENUMBER,VEHICLE.TRANSMISSIONTYPE,VEHICLE.ASSIGNEDAGENCYID,VEHICLE.MILEAGE,
 VEHICLE_STATUS.VEHICLESTATUS,VEHICLE_STATUS.VEHICLESTATUSID
 FROM VEHICLE, VEHICLE_STATUS
 WHERE VEHICLE.VEHICLESTATUSID = VEHICLE_STATUS.VEHICLESTATUSID;
 
--THIRD VIEW
CREATE VIEW Vehicle_Status_View AS
 SELECT VEHICLE.VINNUMBER,VEHICLE.MAKE,VEHICLE.MODEL,VEHICLE.COLOR,VEHICLE.PLATENUMBER,VEHICLE.DAILYRENTALCOST,VEHICLE.ASSIGNEDAGENCYID,VEHICLE.CURRENTAGENCYID,
 VEHICLE.VEHICLETYPE,VEHICLE_STATUS.VEHICLESTATUS,VEHICLE_STATUS.VEHICLESTATUSID
 FROM VEHICLE, VEHICLE_STATUS
 WHERE VEHICLE.VEHICLESTATUSID = VEHICLE_STATUS.VEHICLESTATUSID;
 
--FOURTH VIEW
CREATE VIEW Reservation_Status_View AS
SELECT RESERVATION.CONFIRMATIONID,RESERVATION.DRIVERLICENSENUM,CUSTOMER.FIRSTNAME,CUSTOMER.LASTNAME,CUSTOMER.EMAIL,
RESERVATION_STATUS.RESERVATIONSTATUS,RESERVATION_STATUS.RESERVATIONSTATUSID
FROM CUSTOMER, RESERVATION, RESERVATION_STATUS
WHERE RESERVATION.DRIVERLICENSENUM = CUSTOMER.DRIVERLICENSENUM AND RESERVATION_STATUS.RESERVATIONSTATUSID = RESERVATION.RESERVATIONSTATUSID;

--FIFTH VIEW
CREATE VIEW Earned_Discounts AS
SELECT CUSTOMER.DRIVERLICENSENUM,CUSTOMER.FIRSTNAME,CUSTOMER.LASTNAME,CUSTOMER.EMAIL,PRIVATE_CUSTOMER.EZPLUSNUMBER,EZPLUS.EZPLUSEARNEDPOINTS
FROM CUSTOMER, PRIVATE_CUSTOMER, EZPLUS
WHERE CUSTOMER.DRIVERLICENSENUM = PRIVATE_CUSTOMER.PDRIVERLICENSENUM AND PRIVATE_CUSTOMER.EZPLUSNUMBER = EZPLUS.EZPLUSNUMBER;
 