--SECONDARY INDEX FOR FIRST REPORT
CREATE INDEX Ind_VehicleVSID ON Vehicle(VehicleStatusID);
 
 --SECONDARY INDEX FOR SECOND REPORT (ALSO USES THE INDEX FOR THE FIRST REPORT)
CREATE INDEX Ind_VehicleVSID ON Vehicle(VehicleStatusID);
CREATE INDEX Ind_Mileage ON Vehicle(Mileage);
 
--SECONDARY INDEX FOR THIRD REPORT (USES THE INDEX FOR THE FIRST REPORT)
CREATE INDEX Ind_VehicleVSID ON Vehicle(VehicleStatusID);

--SECONDARY INDEX FOR FOURTH REPORT (USES THE INDEX FOR THE FIRST REPORT)
CREATE INDEX Ind_VehicleVSID ON Vehicle(VehicleStatusID);

--SECONDARY INDEX FOR FIFTH REPORT (USES THE INDEX FOR THE FIRST REPORT)
CREATE INDEX Ind_VehicleVSID ON Vehicle(VehicleStatusID);

--SECONDARY INDEX FOR SIXTH REPORT
CREATE INDEX Ind_ReserveDLNum ON Reservation(DriverLicenseNum);
CREATE INDEX Ind_ReserveRSID ON Reservation(ReservationStatusID);

--SECONDARY INDEX FOR SEVENTH REPORT (USES THE INDEXES FOR THE SIXTH REPORT)
CREATE INDEX Ind_ReserveDLNum ON Reservation(DriverLicenseNum);
CREATE INDEX Ind_ReserveRSID ON Reservation(ReservationStatusID);

--SECONDARY INDEX FOR EIGTH REPORT (USES THE INDEXES FOR THE SIXTH REPORT)
CREATE INDEX Ind_ReserveDLNum ON Reservation(DriverLicenseNum);
CREATE INDEX Ind_ReserveRSID ON Reservation(ReservationStatusID);

--SECONDARY INDEX FOR THE NINTH REPORT
CREATE INDEX Ind_PCustEZPN ON Private_Customer(EZPlusNumber);
CREATE INDEX Ind_EZPEarnedPts ON EZPLUS(EZPlusEarnedPoints);

--SECONDARY INDEX FOR THE TENTH REPORT (USES THE INDEXES FOR THE NINTH REPORT)
CREATE INDEX Ind_PCustEZPN ON Private_Customer(EZPlusNumber);
CREATE INDEX Ind_EZPEarnedPts ON EZPLUS(EZPlusEarnedPoints);